export const keywordsForMetaData:Array<string> = [
    "FastDrop",
    "P2P file sharing",
    "Real-time chat",
    "Swift file transfer",
    "Peer-to-peer connection",
    "Secure data exchange",
    "WebRTC file sharing",
    "Next.js app",
    "Typescript file sharing",
    "Fast data transfer",
    "Instant messaging",
    "Peer-to-peer communication",
    "Fast and secure file sharing",
    "Efficient file exchange",
    "Web app for file sharing",
    "Next.js with TypeScript",
    "Lightning-fast file transfer",
    "Chat and file sharing",
    "FastDrop web application",
    "Seamless data exchange",
    "Quick file sharing",
    "Easy P2P connection",
    "Secure file transfer",
    "User-friendly file sharing",
    "Real-time file exchange",
    "Next.js development",
    "Web app development",
    "FastDrop features",
    "File sharing platform",
    "Secure chat and file transfer",
    "Peer-to-peer collaboration",
    "Efficient data sharing",
    "Next.js TypeScript app",
    "Modern file sharing",
    "Fast and reliable file exchange",
    "WebRTC chat and file sharing",
    "Next.js development services",
    "P2P file transfer",
    "FastDrop benefits"
  ]